# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(default=0, upload_to='router_specifications'),
            preserve_default=False,
        ),
    ]
