# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vids', '0002_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(upload_to='vids/static/img'),
        ),
    ]
